-- MySQL Script generated by MySQL Workbench
-- Sat Jan 11 02:02:26 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tbl_support`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_support` (
  `Telephone` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Epon` VARCHAR(45) NOT NULL,
  `Msg` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Telephone`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_pay`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_pay` (
  `Cash` DOUBLE NOT NULL,
  `CardExpDate` DATE NOT NULL,
  `CardNum` VARCHAR(15) NOT NULL,
  `CardCvv` VARCHAR(3) NOT NULL,
  `CardName` VARCHAR(45) NOT NULL,
  `Telephone` VARCHAR(10) NOT NULL,
  `Card` VARCHAR(2) BINARY NOT NULL,
  UNIQUE INDEX `CardNum_UNIQUE` (`CardNum` ASC) VISIBLE,
  UNIQUE INDEX `UserID_UNIQUE` (`Telephone` ASC) VISIBLE,
  PRIMARY KEY (`Card`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_user` (
  `UserID` INT NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Floor` VARCHAR(45) NOT NULL,
  `Bell` VARCHAR(45) NOT NULL,
  `Telephone` VARCHAR(10) NOT NULL,
  UNIQUE INDEX `Password_UNIQUE` (`Password` ASC) VISIBLE,
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `Telephone_UNIQUE` (`Telephone` ASC) VISIBLE,
  CONSTRAINT `fk_User_UserSupport1`
    FOREIGN KEY (`Email`)
    REFERENCES `mydb`.`tbl_support` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_guest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_guest` (
  `Telephone` VARCHAR(10) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Floor` VARCHAR(45) NOT NULL,
  `Bell` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Telephone`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  CONSTRAINT `fk_Guest_UserSupport1`
    FOREIGN KEY (`Email`)
    REFERENCES `mydb`.`tbl_support` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_shop` (
  `ShopID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Phone` VARCHAR(45) NOT NULL,
  `Rating` DOUBLE NULL,
  PRIMARY KEY (`ShopID`),
  UNIQUE INDEX `Phone_UNIQUE` (`Phone` ASC) VISIBLE,
  UNIQUE INDEX `Address_UNIQUE` (`Address` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_order` (
  `OrderID` VARCHAR(45) NOT NULL,
  `UserID` VARCHAR(45) NOT NULL,
  `ShopID` VARCHAR(45) NOT NULL,
  `TotalPrice` DOUBLE NOT NULL,
  `Telephone` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`OrderID`),
  UNIQUE INDEX `UserID_UNIQUE` (`UserID` ASC) VISIBLE,
  UNIQUE INDEX `ShopID_UNIQUE` (`ShopID` ASC) VISIBLE,
  UNIQUE INDEX `Telephone_UNIQUE` (`Telephone` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Guest1`
    FOREIGN KEY (`Telephone`)
    REFERENCES `mydb`.`tbl_guest` (`Telephone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_User1`
    FOREIGN KEY (`Telephone`)
    REFERENCES `mydb`.`tbl_user` (`Telephone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_PaymentMethod1`
    FOREIGN KEY (`Telephone`)
    REFERENCES `mydb`.`tbl_pay` (`Telephone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_cart` (
  `OrderID` VARCHAR(45) NOT NULL,
  `Piece` INT NOT NULL DEFAULT 0,
  `Price` INT NOT NULL,
  `TotalPrice` VARCHAR(45) NOT NULL,
  `ProdName` VARCHAR(45) NOT NULL,
  `ID_Order` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`OrderID`),
  UNIQUE INDEX `OrderID_UNIQUE` (`OrderID` ASC) VISIBLE,
  UNIQUE INDEX `Order_ID_UNIQUE` (`ID_Order` ASC) VISIBLE,
  CONSTRAINT `fk_Cart_Order1`
    FOREIGN KEY (`ID_Order`)
    REFERENCES `mydb`.`tbl_order` (`OrderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tbl_fooditem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tbl_fooditem` (
  `ItemID` INT NOT NULL,
  `IngrID` VARCHAR(45) NOT NULL,
  `IngrName` VARCHAR(45) NOT NULL,
  `ShopID` INT NOT NULL,
  `CategoryID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ItemID`),
  UNIQUE INDEX `IngrID_UNIQUE` (`IngrID` ASC) VISIBLE,
  UNIQUE INDEX `ShopID_UNIQUE` (`ShopID` ASC) VISIBLE,
  UNIQUE INDEX `CategoryID_UNIQUE` (`CategoryID` ASC) VISIBLE,
  INDEX `fk_FoodItem_Cart1_idx` (`IngrName` ASC) VISIBLE,
  CONSTRAINT `fk_FoodItem_Shop1`
    FOREIGN KEY (`ShopID`)
    REFERENCES `mydb`.`tbl_shop` (`ShopID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FoodItem_Cart1`
    FOREIGN KEY (`IngrName`)
    REFERENCES `mydb`.`tbl_cart` (`ProdName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
